name: CI Pipeline

on: [push, pull_request]   # triggers: when you push or make a PR

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub gives you a Linux VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Runt test
        run: python3 test.py